### PR TITLE
Var run inconsistency

### PR DESCRIPTION
**Pull request by schaefi**
/var/run is a symlink to /run on newer systems and a directory on older systems. We need to properly handle that

### CODE REVIEW

**Comment by mmohring** [comment]
Hi, the "/var/run" change seems to make CentOS 6.x, RHEL 6.x and SUSE SLE 11 SP3 run into an error (other distros might also be affected). The newer distros CentOS 7.x, RHEL 7.x, SLE 12, openSUSE 13.x etc. are working. I am using KIWI within OBS. I get now the following errors:

- RHEL 6.x, CentOS 6.x

[ 1345s] + /usr/bin/yum -c /var/cache/kiwi/yum/yum.conf -y --installroot=/usr/src/packages/KIWIROOT-vmx install basesystem filesystem yum
[ 1346s] Could not open lock /usr/src/packages/KIWIROOT-vmx/var/run/yum.pid: [Errno 2] No such file or directory: '/usr/src/packages/KIWIROOT-vmx/var/run/yum.pid'
[ 1346s] Can't create lock file; exiting

- SUSE SLE 11 SP3 (potentially all SLE 11 I guess):

[  712s] + /usr/bin/zypper --non-interactive --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /usr/src/packages/KIWIROOT-vmx//var/cache/kiwi/zypper/repos --solv-cache-dir /usr/src/packages/KIWIROOT-vmx//var/cache/kiwi/zypper/solv --cache-dir /usr/src/packages/KIWIROOT-vmx//var/cache/kiwi/zypper --config /var/cache/kiwi/zypper/zypper.conf.3848 --no-gpg-checks --root /usr/src/packages/KIWIROOT-vmx install --auto-agree-with-licenses --no-recommends filesystem glibc-locale bootsplash-branding-SLES gfxboot gfxboot-branding-SLES vmware-guest-kmp-default xen-kmp-default zypper
[  712s] Cant open /usr/src/packages/KIWIROOT-vmx/var/run/zypp.pid

**Comment by schaefi** [comment]
Hrm, not so good, what build system distro was used to build rhel and/or sle11 ?

I will give sle11 a try to see if that happens on my test system too

Thanks

**Comment by schaefi** [comment]
kiwi --build  template/ix86/suse-SLE11-JeOS/ -d /tmp/mytest --type vmx on a 13.2 build box did not complain

**Comment by mmohring** [comment]
KIWI on OBS always uses target OS = host OS. E.g. if you build SLE 11 SP3 target it also uses SLE 11 SP3 host.

**Comment by schaefi** [comment]
giving rhel a test

**Comment by schaefi** [comment]
kiwi --build  template/ix86/rhel-06.6-JeOS/ -d /tmp/mytest --type vmx on the same build box also does not complain

**Comment by schaefi** [comment]
Hmm, I'm wondering what happens. actually this is only changing from a dir to a symlink that should not introduce any inconsistency.... last famous words

**Comment by mmohring** [comment]
And I am using the KIWI provided templates for VMX, e.g. for SLE 11 SP3 I use:

type compressed="false" image="vmx" filesystem="ext4" boot="vmxboot/suse-SLES11" format="vmdk" fsnocheck="true" bootloader="grub"

E.g. I use the standard KIWI provided "vmxboot/suse-SLES11" VMX template.

**Comment by mmohring** [comment]
Last KIWI version working was: 7.03.13. So it could be another change between 7.03.13 and 7.03.17 of course. It was just the coincidence of your title "/var/run" and yum respectively zypper complaining about some lock file missing in its local /var/run directory that made me look into this.

**Comment by mmohring** [comment]
I can raise an own issue if you like and move this discussion away from issue #486.

**Comment by schaefi** [comment]
yes that would be good, thanks

**Comment by mmohring** [comment]
Done, the issue is  #487.

**Pull request merged**
