### PR TITLE
Solving some broken dialogs

### PR DESCRIPTION
**Pull request by davidcassany**
HideSplash method used to hide the splash only if there was an active console, however the dialogs appear broken if the splash isn't hidden and in some cases is hard to check if there is an active consoles (i.e. after umount /sys or mount --move /dev /mnt/dev).

This commit fixes bnc#997085

### CODE REVIEW

**Comment by schaefi** [comment]
Looks good to me, we need this in the v8 code base too. The patch should apply without conflicts to kiwi/boot/functions.sh. Do you want me to port it over once this is merged or do you care for it too ?

Thanks

**Comment by schaefi** [comment]
:+1:

**Comment by davidcassany** [comment]
I will port it to kiwi v8, it will be easy, I have already located the code.  thanks

**Comment by schaefi** [comment]
Thanks that's great

**Comment by schaefi** [comment]
Another point to discuss. The commit message says this commit tries to fix it... that doesn't sound very confident :smile: So do we know if it fixes the broken dialog or do we just guess ? If we know it fixes a certain condition we should explain that condition and raise our hands for other scenarios.

Thoughts ?

**Comment by davidcassany** [comment]
Yes, you are right. I know it solves some some issues, concretely, it solves the dialogs that appear if oem-reboot-interactive or oem-shutdown-interactive flags are set. However I have not tested the progress dialogs that may appear in a netboot (I guess due to fetchFile method), I tried to set a virtual server/client env but I did not succeed up to now. I suspect in that concrete case it might happen that the hideSplash method is never called, thus the splash keeps being visible and if the user presses 'ESC' key then a broken dialog with a progress bar should appear. In that concrete case it is not that critic since the progress bar wouldn't be demanding any user interaction, so the boot would just run fine, but with an ungly dialog trying to show a download progress. All that said, this is just a guess, as I could not test it yet.

**Comment by schaefi** [comment]
That's fair enough, so if you don't mind remove the "tries" from the commit message and say that it fixes the broken dialog scenarios reported in bnc#997085 because that's the truth. If the QA testing will find that the bug is only partially fixed we can reference a follow up fix on the same bug. But that we tried our best and failed will not highlight the work and effort you spent on it :)

**Comment by davidcassany** [comment]
Ok done. However I managed to reproduce the bug with a pxe image, as I suspected hideSplash is not called in the fetchFile method. I am about to include another commit to fix it. Now testing it, I am pretty sure that adding hideSplash call will be suficient.

**Comment by schaefi** [comment]
cool, I'll wait with the merge ;)

**Comment by davidcassany** [comment]
Ok, now I definitely tested it in all the scenarios reported in bnc#997085. Those broken dialogs are fixed now.

**Pull request merged**
