### PR TITLE
Fix VMWare disk tagging

### PR DESCRIPTION
**Pull request by bear454**
The current implementation had a few issues resulting in nonfunctional VMDKs:

screenshot from 2016-07-06 14-13-24

### CODE REVIEW

**Comment by schaefi** [comment]
Thanks for the patch, that was a bad bug introduced by myself :disappointed: 

perlcritic complains about:

```
 "my" variable $data masks earlier declaration in same scope at /home/travis/build/openSUSE/kiwi/tests/unit/../../modules/KIWIImageFormat.pm line 1551.

Scalar value @descriptor_lines[0] better written as $descriptor_lines[0] at /home/travis/build/openSUSE/kiwi/tests/unit/../../modules/KIWIImageFormat.pm line 1554.

syntax error at /home/travis/build/openSUSE/kiwi/tests/unit/../../modules/KIWIImageFormat.pm line 1552, near "my "
```

**Comment by bear454** [comment]
@schaefi: fixed up; sorry for the mistakes... my Perl Fu is weak :/

**Comment by bear454** [comment]
Fixes https://bugzilla.suse.com/show_bug.cgi?id=988086 , https://bugzilla.suse.com/show_bug.cgi?id=988087

**Comment by schaefi** [comment]
Thanks looks good now :+1:

**Pull request merged**
