### PR TITLE
mediacheck: give the user 5s time to actually see the result (also helps...

### PR DESCRIPTION
**Pull request by DimStar77**
... openQA to catch it) - Failure waits for user input already

### CODE REVIEW

**Comment by schaefi** [comment]
yeah makes sense :)

being picky but could you fix the indention (4 spaces), thanks

**Comment by DimStar77** [comment]
Sure - I missed that vi so nicely auto-indented but used a tab instead of spaces.. .corrected.

**Comment by schaefi** [comment]
ok, just another little thing, we should at least mention that we are waiting for 5sec and that one can continue by pressing any key. Thus could you add another Echo statement like

```
Echo "Press any key to continue (waiting 5 sec...)"
```

**Comment by schaefi** [comment]
and maybe put the time in a variable

**Comment by DimStar77** [comment]
ok, time is in a variable, and I changed the read call to be
-s -n 1 -t <timeout)

-s => do not echo whatever input we get from the CLI if any (just looks neater)
-n 1 => actually do as we advertise: ANY key is sufficient (otherwise read waits for EOL)

**Comment by schaefi** [comment]
great :) will merge it

**Pull request merged**
